### ISSUE TITLE
How to make it select the area(point of displacement) manually and not automatically. Please suggest!

### ISSUE THREAD

**Issue by saberclaw1213** [kevroy314/respmon#2]

**Comment by kevroy314** [comment]
At one point, I had it supporting manual calibration. I'm not sure why I took it out, but the easiest way to get around it would be to add the following line to the beginning of the calibration state in the primary state machine (i.e. here https://github.com/kevroy314/respmon/blob/master/base.py#L427)

```
self.skip_calibration(x, y, w, h)
```

where x, y, w, h are integers defining your bounding box. I haven't tested this, but I think that should probably do it.

Note that you can call that wherever you'd like (i.e. outside the object), but all it will do is force the object into the measurement phase with some parameters set. Next time an error occurs (i.e. you lose motion tracking) it will recalibrate. So you could, alternatively, monitor the `state` variable for `'error'` and bypass calibration with `skip_calibration`. The nice thing about that would be you wouldn't need to modify the object code.

If you'd like to modify the constructor/state machine to support an override mode for that operation, I'd be happy to merge it in if you send me a PR.
